MODULE MODD_BUF
  TYPE BUF_t
    REAL :: XX
  END TYPE BUF_t
END MODULE MODD_BUF

SUBROUTINE ADD(Z1, Z2, &
               PBUF)
USE MODD_BUF, ONLY : BUF_t
IMPLICIT NONE
REAL, INTENT(IN) :: Z1, Z2
TYPE(BUF_t), INTENT(IN) :: PBUF
END SUBROUTINE ADD
